name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run proxy check script
      run: |
        python main.py

    - name: List files for debugging
      run: |
        echo "Current directory:"
        pwd
        echo "Files in current directory:"
        ls -la

    - name: Prepare docs directory
      run: |
        mkdir -p docs
        cp ./good.txt docs/
        echo 'your.custom.domain' > docs/CNAME  # 保留自定义域名

    - name: List files in docs directory
      run: |
        echo "Files in docs directory:"
        ls -la docs/

    - name: Set up Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Move untracked files
      run: |
        mv good.txt /tmp/good.txt || true

    - name: Checkout and update gh-pages
      run: |
        git fetch origin gh-pages
        git checkout -B gh-pages
        git reset --hard origin/gh-pages
        mv /tmp/good.txt ./docs/http.txt || true

    - name: Commit and push to gh-pages
      run: |
        git add docs/
        git commit -m 'Deploy proxies to GitHub Pages' || echo "No changes to commit"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
