name: Proxy Check

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:

jobs:
  proxy-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install requests colorama tqdm

    - name: Run proxy check script
      run: |
        python main.py

    - name: Upload proxies to GitHub Pages
      run: |
        cp ./proxy/proxy/http.txt ./docs/
    
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add ./docs/http.txt
        git commit -m "Update proxy file"
        git push
