name: Proxy Check

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:

jobs:
  proxy-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install requests colorama tqdm

    - name: Run proxy check script
      run: |
        python main.py

    - name: Set up gh-pages branch
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        # Ensure we are on the gh-pages branch and create it if it doesn't exist
        git checkout gh-pages || git checkout -b gh-pages
        # Create directory structure
        mkdir -p proxy/proxy
        # Copy the good.txt file to the proxy directory
        cp good.txt proxy/proxy/http.txt

    - name: Commit and push changes
      run: |
        git add proxy/proxy/http.txt
        git commit -m 'Update valid proxies'
        git push origin gh-pages
