name: Proxy Check

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:

jobs:
  proxy-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install requests colorama tqdm

    - name: Run proxy check script
      run: |
        python main.py

    # 添加步骤：将生成的 good.txt 文件复制到 gh-pages 分支
    - name: Checkout gh-pages branch
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git checkout gh-pages || git checkout --orphan gh-pages
        cp good.txt ./proxy/proxy/http.txt
        git add .
        git commit -m 'Update good.txt with valid proxies'
        git push origin gh-pages
